version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
  dbmysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: frame
    ports:
     - "3308:3306"
  admin:     
    image: adminer     
    ports:       
     - "8080:8080"